---
title: "SOK-2008-2022-oppgave5"
output: pdf_document
author: "Håvard Chramer"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PxWebApiData)
library(forecast)
library(janitor)
theme_set(theme_bw())
```


# Utfordring 5.1
## 1. 

```{r}
innvandrere <- 
  ApiData("https://data.ssb.no/api/v0/no/table/05185/", 
          Landbakgrunn=list('agg:Verdensdel2', c("b11", "b12", "b13", "b14", 
                                                 "b2", "b3", "b4", "b5", "b6")), 
          Tid=list('item', c("2005", "2006", "2007", "2008", "2009", "2010", 
                             "2011", "2012", "2013", "2014", "2015", "2016", 
                             "2017", "2018", "2019", "2020", "2021", "2022")), 
          Kjonn=FALSE, 
          ContentsCode=TRUE)

innvandrere <- as.tibble(innvandrere[[1]])

innvandrere[-2] %>%
  pivot_wider(names_from = år, values_from = value)

innvandrere <- innvandrere %>% 
  arrange(år)

ggplot(innvandrere, aes(x = value, y = år, fill = landbakgrunn)) +
  geom_col() +
  labs(x = "",
       y = "",
       title = "Innvandring totalt 2005 til 2022") +
  scale_fill_discrete(name = "Verdensdeler")
```

```{r}
innvandrere <- innvandrere %>% 
  group_by(år) %>% 
  mutate(sum = sum(value),
         andel = value/sum,
         andel = round(andel*100, digits = 1)) %>% 
  select(-sum)

ggplot(innvandrere, aes(x = andel, y = år, fill = landbakgrunn)) +
  geom_col() +
  geom_text(aes(label = paste0(andel, '%')), 
            position = position_stack(vjust = 0.5), color = "black", size = 2) +
  labs(x = "",
       y = "",
       title = "Innvandring i prosent 2005 til 2022") +
  scale_fill_discrete(name = "Verdensdeler") +
    theme(legend.key.height= unit(0.1, 'cm'),
        legend.key.width= unit(0.1, 'cm'),
        legend.text = element_text(size=5),
        legend.title = element_text(size=10))
```

## 2.

```{r}
sektorer <- 
  ApiData("https://data.ssb.no/api/v0/no/table/13215/", 
          Kjonn=list('item', c("0")), 
          Alder=list('item', c("15-74")), 
          InnvandrKat=list('item', c("B")), 
          Landbakgrunn=list('item', c("015a")), 
          NACE2007=list('agg:NACE260InnvGrupp2',
                        c("SNI-00-99", "SNI-01-03", "SNI-05-09", "SNI-10-33",
                          "SNI-35-39", "SNI-41-43", "SNI-45-47", "SNI-49-53",
                          "SNI-49.3", "SNI-55", "SNI-56", "SNI-58-63",
                          "SNI-64-66", "SNI-68-75", "SNI-77-82", "SNI-78.2",
                          "SNI-81.2", "SNI-84","SNI-85","SNI-86-88","SNI-90-99",
                          "SNI-00")), 
          Tid=list('item', c("2021")), 
          ContentsCode=TRUE)

sektorer <- as.tibble(sektorer[[1]])

sektorer <- sektorer %>% 
  select(`næring (SN2007)`, value) %>% 
  arrange(desc(value))

sektorer$`næring (SN2007)` <- gsub(".*\\.", "", sektorer$`næring (SN2007)`)


sektorer[-1,] %>%
  ggplot(aes(x = `næring (SN2007)`, y = value, fill = `næring (SN2007)`)) +
  geom_col(show.legend = FALSE) +
  labs(x = "",
       y = "",
       title = "Næringslivssektor blant innvandrere fra EU-land i Øst-Europa") +
  theme(text = element_text(size=7),
        axis.text.x = element_text(angle=90, hjust=1))
```



